FROM public.ecr.aws/docker/library/node:10-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 80

RUN chmod +x scripts/entrypoint.sh

ENTRYPOINT ["/usr/src/app/scripts/entrypoint.sh"]
